"""Generate the blank "Factory Audit Report" template the upload pages link to.

Produces BOTH formats from one content definition:
  - backend/static/sample_audit_template.docx   (python-docx)
  - backend/static/sample_audit_template.pdf     (reportlab)

The same two files are also copied into web/public/ so the web app can serve
them as static downloads. The mobile app downloads them from the backend's
/static mount.

Usage (from backend/):
    python scripts/generate_audit_template.py
"""
from __future__ import annotations

import shutil
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = BACKEND_DIR / "static"
WEB_PUBLIC_DIR = BACKEND_DIR.parent / "web" / "public"

BACKEND_URL = "exportiq-backend-495022768388.us-central1.run.app"
FOOTER = (
    f"Generated by ExportIQ · {BACKEND_URL} · "
    "For EU/UK textile export compliance · Pakistan"
)
BOX = "☐"  # ☐ ballot box

CERT_ROWS = ["SA8000", "ISO 14001", "OEKO-TEX", "GOTS"]


# ─────────────────────────────────────────────────────────────────────────────
# DOCX
# ─────────────────────────────────────────────────────────────────────────────
def build_docx(out_path: Path) -> None:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    TEAL = RGBColor(0x00, 0xC4, 0x8C)
    doc = Document()

    title = doc.add_heading("ExportIQ — Factory Audit Report Template", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub = doc.add_paragraph("For EU/UK textile export compliance · Pakistan")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER

    def section(num: int, name: str, hint: str | None = None):
        h = doc.add_heading(f"Section {num}: {name}", level=1)
        for run in h.runs:
            run.font.color.rgb = TEAL
        if hint:
            p = doc.add_paragraph()
            r = p.add_run(hint)
            r.italic = True
            r.font.size = Pt(9)

    def field(label: str, hint: str = ""):
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run("_______________________________")
        if hint:
            r = p.add_run(f"   ({hint})")
            r.italic = True
            r.font.size = Pt(9)

    def table(headers: list[str], rows: list[list[str]]):
        t = doc.add_table(rows=1, cols=len(headers))
        t.style = "Light Grid Accent 1"
        for i, head in enumerate(headers):
            cell = t.rows[0].cells[i]
            cell.text = head
            for para in cell.paragraphs:
                for run in para.runs:
                    run.bold = True
        for row in rows:
            cells = t.add_row().cells
            for i, val in enumerate(row):
                cells[i].text = val

    # 1
    section(1, "FACTORY INFORMATION")
    field("Factory Name")
    field("City / Province")
    doc.add_paragraph("Country: Pakistan")
    field("Factory Size (employees)")
    field("Annual Export Volume (PKR)")
    doc.add_paragraph(f"Primary Export Markets:  {BOX} EU   {BOX} UK   {BOX} USA   {BOX} Other")

    # 2
    section(2, "BUYER INFORMATION", "List all active EU/UK buyers.")
    table(
        ["Buyer Name", "Country", "Annual Order Value (PKR)", "Regulation Applicable"],
        [["", "", "", ""], ["", "", "", ""], ["", "", "", ""]],
    )

    # 3
    section(3, "CERTIFICATIONS")
    table(
        ["Certification", "Status", "Issue Date", "Expiry Date", "Certifying Body"],
        [[c, "", "", "", ""] for c in CERT_ROWS],
    )

    # 4
    section(4, "ENVIRONMENTAL DATA")
    field("Water effluent discharge level (ppm)", "EU limit: 8 ppm")
    field("Chemical dyes used (list SVHC substances if any)")
    field("Annual CO2 emissions (tonnes)", "required for EU CBAM")
    field("Embedded carbon per unit (kgCO2)")

    # 5
    section(5, "LABOUR COMPLIANCE")
    field("Average weekly working hours (incl. overtime)", "EU limit: 48 hrs")
    field("Minimum age of workers")
    doc.add_paragraph(f"Modern slavery / forced labour policy in place:  {BOX} Yes   {BOX} No")
    doc.add_paragraph(f"UK Modern Slavery Act s.54 statement published:  {BOX} Yes   {BOX} No   {BOX} N/A")
    doc.add_paragraph(f"Grievance mechanism in place:  {BOX} Yes   {BOX} No")

    # 6
    section(6, "SUPPLY CHAIN")
    doc.add_paragraph(f"Tier-1 suppliers listed:  {BOX} Yes   {BOX} No")
    doc.add_paragraph(f"Tier-2 suppliers mapped:  {BOX} Yes   {BOX} No")
    doc.add_paragraph(f"Supply chain due diligence policy:  {BOX} Yes   {BOX} No   (required for EU CSDDD)")

    # 7
    section(7, "SELF-REPORTED CLAIMS", "List any compliance claims your factory makes.")
    for _ in range(3):
        doc.add_paragraph("_______________________________________________________")

    # 8
    section(8, "PREVIOUS AUDIT FINDINGS", "Summarise findings from your last audit and corrective actions taken.")
    for _ in range(3):
        doc.add_paragraph("_______________________________________________________")

    doc.add_paragraph()
    foot = doc.add_paragraph(FOOTER)
    foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in foot.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.save(str(out_path))


# ─────────────────────────────────────────────────────────────────────────────
# PDF
# ─────────────────────────────────────────────────────────────────────────────
def build_pdf(out_path: Path) -> None:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    TEAL = colors.HexColor("#00C48C")
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("T", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#0D1117")))
    styles.add(ParagraphStyle("Sec", parent=styles["Heading2"], fontSize=12, textColor=TEAL, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle("B", parent=styles["Normal"], fontSize=10, leading=16))
    styles.add(ParagraphStyle("Hint", parent=styles["Normal"], fontSize=8, textColor=colors.grey, leading=12))
    styles.add(ParagraphStyle("Cell", parent=styles["Normal"], fontSize=9, leading=12))
    styles.add(ParagraphStyle("Foot", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=1))

    # reportlab's built-in Helvetica has no ballot-box / em-dash / middot
    # glyphs, so the PDF uses ASCII-safe substitutes (the DOCX keeps the nicer
    # Unicode versions).
    box = "[ ]"
    footer_pdf = f"Generated by ExportIQ  |  {BACKEND_URL}  |  EU/UK textile export compliance  |  Pakistan"

    story: list = []
    story.append(Paragraph("ExportIQ - Factory Audit Report Template", styles["T"]))
    story.append(Paragraph("For EU/UK textile export compliance - Pakistan", styles["Hint"]))
    story.append(Spacer(1, 10))

    def sec(num, name, hint=None):
        story.append(Paragraph(f"Section {num}: {name}", styles["Sec"]))
        if hint:
            story.append(Paragraph(hint, styles["Hint"]))

    def field(label, hint=""):
        extra = f' <font color="#888888" size="8">({hint})</font>' if hint else ""
        story.append(Paragraph(f"<b>{label}:</b> ______________________________{extra}", styles["B"]))

    def table(headers, rows, widths):
        data = [[Paragraph(f"<b>{h}</b>", styles["Cell"]) for h in headers]]
        data += [[Paragraph(c, styles["Cell"]) for c in r] for r in rows]
        t = Table(data, colWidths=widths)
        t.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#888888")),
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 6))

    sec(1, "FACTORY INFORMATION")
    field("Factory Name"); field("City / Province")
    story.append(Paragraph("Country: Pakistan", styles["B"]))
    field("Factory Size (employees)"); field("Annual Export Volume (PKR)")
    story.append(Paragraph(f"Primary Export Markets: {box} EU&nbsp;&nbsp; {box} UK&nbsp;&nbsp; {box} USA&nbsp;&nbsp; {box} Other", styles["B"]))

    sec(2, "BUYER INFORMATION", "List all active EU/UK buyers.")
    table(["Buyer Name", "Country", "Annual Order Value (PKR)", "Regulation Applicable"],
          [["", "", "", ""]] * 3, [50 * mm, 28 * mm, 50 * mm, 42 * mm])

    sec(3, "CERTIFICATIONS")
    table(["Certification", "Status", "Issue Date", "Expiry Date", "Certifying Body"],
          [[c, "", "", "", ""] for c in CERT_ROWS],
          [34 * mm, 24 * mm, 28 * mm, 28 * mm, 56 * mm])

    sec(4, "ENVIRONMENTAL DATA")
    field("Water effluent discharge level (ppm)", "EU limit: 8 ppm")
    field("Chemical dyes used (list SVHC substances if any)")
    field("Annual CO2 emissions (tonnes)", "required for EU CBAM")
    field("Embedded carbon per unit (kgCO2)")

    sec(5, "LABOUR COMPLIANCE")
    field("Average weekly working hours (incl. overtime)", "EU limit: 48 hrs")
    field("Minimum age of workers")
    story.append(Paragraph(f"Modern slavery / forced labour policy in place: {box} Yes&nbsp;&nbsp; {box} No", styles["B"]))
    story.append(Paragraph(f"UK Modern Slavery Act s.54 statement published: {box} Yes&nbsp;&nbsp; {box} No&nbsp;&nbsp; {box} N/A", styles["B"]))
    story.append(Paragraph(f"Grievance mechanism in place: {box} Yes&nbsp;&nbsp; {box} No", styles["B"]))

    sec(6, "SUPPLY CHAIN")
    story.append(Paragraph(f"Tier-1 suppliers listed: {box} Yes&nbsp;&nbsp; {box} No", styles["B"]))
    story.append(Paragraph(f"Tier-2 suppliers mapped: {box} Yes&nbsp;&nbsp; {box} No", styles["B"]))
    story.append(Paragraph(f"Supply chain due diligence policy: {box} Yes&nbsp;&nbsp; {box} No&nbsp;&nbsp; (required for EU CSDDD)", styles["B"]))

    sec(7, "SELF-REPORTED CLAIMS", "List any compliance claims your factory makes.")
    for _ in range(3):
        story.append(Paragraph("________________________________________________________", styles["B"]))

    sec(8, "PREVIOUS AUDIT FINDINGS", "Summarise findings from your last audit and corrective actions taken.")
    for _ in range(3):
        story.append(Paragraph("________________________________________________________", styles["B"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph(footer_pdf, styles["Foot"]))

    SimpleDocTemplate(
        str(out_path), pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm, topMargin=18 * mm, bottomMargin=18 * mm,
        title="ExportIQ — Factory Audit Report Template",
    ).build(story)


def main() -> int:
    STATIC_DIR.mkdir(exist_ok=True)
    docx_path = STATIC_DIR / "sample_audit_template.docx"
    pdf_path = STATIC_DIR / "sample_audit_template.pdf"
    build_docx(docx_path)
    build_pdf(pdf_path)
    print(f"wrote {docx_path} ({docx_path.stat().st_size:,} bytes)")
    print(f"wrote {pdf_path} ({pdf_path.stat().st_size:,} bytes)")

    WEB_PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    for src in (docx_path, pdf_path):
        dst = WEB_PUBLIC_DIR / src.name
        shutil.copyfile(src, dst)
        print(f"copied -> {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
