"""Recovery agent — runs when any other agent throws.

This is what the failure-injection demo moment shows in Antigravity Manager
view: an agent failed, the supervisor routes to recovery, recovery produces
a fallback artifact (e.g. a manual booking template instead of the CertVerify API
call), and the pipeline continues to the next agent.
"""
from __future__ import annotations

import logging

from tools.document_generator import generate_audit_checklist
from .base import log_step
from .state import AgentState

log = logging.getLogger("exportiq.agents.recovery")

AGENT_NAME = "recovery"


def run(state: AgentState) -> dict:
    patches: dict = {}
    failed_in = state.get("inject_failure_in") or "unknown_agent"
    failure_type = state.get("inject_failure_type") or "unknown"
    patches.update(log_step(state, AGENT_NAME, "activated",
                            {"failed_agent": failed_in, "failure_type": failure_type}))

    # Produce a fallback artefact so the demo shows recovery clearly
    fallback_doc = {
        "document_id": f"fallback_{failed_in}",
        "title": f"Fallback artifact — {failed_in} unavailable",
        "kind": "REMEDIATION_PLAN",
        "body": (
            f"# Fallback procedure — {failed_in} ({failure_type})\n\n"
            f"The {failed_in} agent reported `{failure_type}` mid-run. Recovery agent took over.\n\n"
            f"**Manual fallback:**\n"
            f"1. Compliance officer initiates manual booking with CertVerify / Bureau Veritas\n"
            f"2. Use the template below to email the audit firm directly\n"
            f"3. Resume the ExportIQ pipeline once external response is received\n\n"
            f"_Generated by recovery_agent. Pipeline will continue with remaining agents._"
        ),
    }

    documents = list(state.get("documents") or []) + [fallback_doc]
    patches["documents"] = documents
    patches["recovery_used"] = True
    # Clear the injection flag so downstream agents proceed normally
    patches["inject_failure_in"] = None
    patches["inject_failure_type"] = None

    patches.update(log_step(state, AGENT_NAME, "fallback_artifact_generated",
                            {"document_id": fallback_doc["document_id"]}))
    return patches
