import React, { useEffect, useState, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  Alert,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

import { colors, radii, shadow, spacing } from '../constants/colors';
import { subscribeReport, updateDocument } from '../services/firebase';
import { openInGmail } from '../services/mail';

function splitSubjectFromBody(rawBody, fallbackTitle) {
  const body = String(rawBody || '');
  // Try the "# Subject: ..." header generated by the email stubs first.
  const lines = body.split('\n');
  for (let i = 0; i < Math.min(3, lines.length); i += 1) {
    const m = lines[i].match(/^\s*#?\s*(?:\*\*)?Subject(?:\*\*)?\s*:?\s*(.+)$/i);
    if (m && m[1]) {
      const subject = m[1].replace(/\*\*/g, '').trim();
      const remainder = lines.slice(i + 1).join('\n').trim();
      return { subject, body: remainder };
    }
  }
  return { subject: fallbackTitle || 'Compliance Status Update', body: body.trim() };
}

export default function EditEmailScreen({ route, navigation }) {
  const { factoryId, documentId, buyer } = route.params || {};
  const [originalDoc, setOriginalDoc] = useState(null);
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [saving, setSaving] = useState(false);
  const [recipient, setRecipient] = useState(buyer || '');

  useEffect(() => {
    if (!factoryId) return;
    const unsub = subscribeReport(factoryId, (report) => {
      if (!report) return;
      const docs = report.documents || [];
      const found = docs.find((d) => (d.document_id || d.id) === documentId);
      if (!found || originalDoc) return; // load once
      setOriginalDoc(found);
      const split = splitSubjectFromBody(found.body, found.title);
      setSubject(split.subject);
      setBody(split.body);
      setRecipient(found.buyer || buyer || '');
    });
    return () => unsub && unsub();
  }, [factoryId, documentId]);

  const onSaveDraft = useCallback(async () => {
    try {
      setSaving(true);
      const composedBody = `# Subject: ${subject}\n\n${body}`;
      await updateDocument(factoryId, documentId, {
        title: subject,
        body: composedBody,
      });
      Alert.alert('Draft saved', 'Your changes have been saved to this email draft.');
      navigation.goBack();
    } catch (e) {
      Alert.alert('Could not save', String(e.message));
    } finally {
      setSaving(false);
    }
  }, [factoryId, documentId, subject, body, navigation]);

  const onOpenInGmail = useCallback(async () => {
    // Hand the draft to the Gmail app (falls back to the default mail app).
    // We never send — the user reviews and sends from Gmail.
    await openInGmail({ to: recipient || '', subject, body });
  }, [recipient, subject, body]);

  if (!originalDoc) {
    return (
      <View style={[styles.bg, { alignItems: 'center', justifyContent: 'center' }]}>
        <Text style={styles.dimText}>Loading email…</Text>
      </View>
    );
  }

  return (
    <KeyboardAvoidingView
      style={styles.bg}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
        {recipient ? (
          <View style={styles.recipientCard}>
            <Ionicons name="mail-outline" size={16} color={colors.textDim} />
            <Text style={styles.recipientText}>To: {recipient}</Text>
          </View>
        ) : null}

        <Text style={styles.label}>Subject</Text>
        <TextInput
          style={styles.subjectInput}
          value={subject}
          onChangeText={setSubject}
          placeholder="Subject line"
          placeholderTextColor={colors.textMuted}
        />

        <Text style={styles.label}>Body</Text>
        <TextInput
          style={styles.bodyInput}
          value={body}
          onChangeText={setBody}
          placeholder="Body of your email"
          placeholderTextColor={colors.textMuted}
          multiline
          textAlignVertical="top"
        />

        <View style={styles.btnRow}>
          <TouchableOpacity
            style={[styles.btn, styles.btnSecondary, saving && { opacity: 0.6 }]}
            onPress={onSaveDraft}
            disabled={saving}
            activeOpacity={0.85}
          >
            <Ionicons name="save-outline" size={16} color={colors.primary} />
            <Text style={styles.btnSecondaryText}>
              {saving ? 'Saving…' : 'Save Draft'}
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.btn, styles.btnPrimary]}
            onPress={onOpenInGmail}
            activeOpacity={0.85}
          >
            <Ionicons name="mail" size={16} color={colors.bg} />
            <Text style={styles.btnPrimaryText}>Open in Gmail App</Text>
          </TouchableOpacity>
        </View>

        <Text style={styles.note}>
          "Open in Gmail App" opens this draft in Gmail (or your default mail
          app) with everything pre-filled. You can send from any signed-in
          account.
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  bg: { flex: 1, backgroundColor: colors.bg },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  dimText: { color: colors.textDim },

  recipientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: spacing.md,
  },
  recipientText: { color: colors.text, marginLeft: 8, fontWeight: '600' },

  label: {
    color: colors.textDim,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: spacing.md,
  },

  subjectInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  bodyInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
    minHeight: 280,
  },

  btnRow: {
    flexDirection: 'row',
    marginTop: spacing.lg,
    gap: spacing.md,
  },
  btn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: radii.md,
    ...shadow,
  },
  btnPrimary: { backgroundColor: colors.primary },
  btnSecondary: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  btnPrimaryText: { color: colors.bg, fontWeight: '800', marginLeft: 8, fontSize: 14 },
  btnSecondaryText: { color: colors.primary, fontWeight: '800', marginLeft: 8, fontSize: 14 },

  note: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: spacing.lg,
  },
});
